package core.basesyntax;

public enum Name {
    JAMES, JOHN, PATRICIA, ROBERT, JENNIFER, MICHAEL, LINDA, WILLIAM, ELIZABETH, DAVID, BARBARA,
    RICHARD, SUSAN, JOSEPH, JESSICA, THOMAS, SARAH, CHARLES, KAREN, CHRISTOPHER, NANCY, DANIEL,
    MARGARET, MATTHEW, LISA, ANTHONY, BETTY, DONALD, DOROTHY, MARK, SANDRA, PAUL, ASHLEY, STEVEN,
    KIMBERLY, ANDREW, DONNA, KENNETH, EMILY, JOSHUA, MICHELLE, GEORGE, CAROL, KEVIN, AMANDA, BRIAN;
}
